### ISSUE TITLE
DATINGCRITERION

### ISSUE THREAD

**Issue by lmarinucci** [misael77/IDEHAdataset#15]
BERT non sembra funzionare in alcuni casi (es. riga 306: sull' documentazione).

**Comment by lmarinucci** [comment]
La prima variabile con la datazione viene tolta direttamente nel template.

**Comment by LuanaBulla** [comment]
Il problema è dovuto al template (la frase data in input non contiene le parentesi quadre con le varie alternative quindi il programma non la riconosce e non la processa tramite Bert). Sarebbe possibile modificare l'answer nel template con: "La datazione ${eventTimeLabel} del bene culturale si basa [sull'/sulla] ${CriterionLabel}." ?
