### ISSUE TITLE
ADDRESS Separare i casi in cui c'è solo regione e nazione senza indirizzo

### ISSUE THREAD

**Issue by misael77** [misael77/IDEHAdataset#3]

**Comment by LuanaBulla** [comment]
Ho aggiunto un'alternativa qualora non dovesse essere presente un risultato per "fullAddress" ("L'indirizzo del bene culturale si trova.."). Ho riscontrato però un problema con l'elaborazione della query e credo sia dovuto al fatto che la variabile 'depiction' sia stata usata ma non assegnata.

**Comment by misael77** [comment]
Ho aggiunto la depiction alla query. Ora dovrebbe essere a posto
